### ISSUE TITLE
With your startup parameters, tensorboard starts up, but it won't be able to read s3 logs

### ISSUE THREAD

**Issue by weAreFriendYo** [kaenova/tensorboard-s3#1]
No dashboards are active for the current data set.
Probable causes:

You haven’t written any data to your event files.
TensorBoard can’t find your event files.
If you’re new to using TensorBoard, and want to find out how to add data and set up your event files, check out the [README](https://github.com/tensorflow/tensorboard/blob/master/README.md) and perhaps the [TensorBoard tutorial](https://www.tensorflow.org/get_started/summaries_and_tensorboard).
If you think TensorBoard is configured properly, please see [the section of the README devoted to missing data problems](https://github.com/tensorflow/tensorboard/blob/master/README.md#my-tensorboard-isnt-showing-any-data-whats-wrong) and consider filing an issue on GitHub.

Last reload: Apr 16, 2024, 5:40:35 PM
Log directory: s3://bucketname/tensorboard_log/

**Comment by kaenova** [comment]
@weAreFriendYo 
Thank you for raising this issue. Last time I checked there was no problem and i can run it smoothly. I may need your environment parameters when you run the docker image. Please redact any private data you have.

**Comment by kaenova** [comment]
Regarding the environment variables, I might forgot to add `S3_ENDPOINT` as required environment variables to the README. Here's my docker compose to test the image on my development environment.

```yaml
version: "3.8"

services:
  minio:
    image: quay.io/minio/minio:latest
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - "MINIO_ROOT_USER=ROOTNAME"
      - "MINIO_ROOT_PASSWORD=CHANGEME123"

  tb:
    image: kaenova/tensorboard-s3
    ports:
      - "6006:6006"
    environment:
      - "S3_BUCKET_NAME=s3-test"
      - "S3_ENDPOINT=http://minio:9000"
      - "LOGDIR=tensorboard"
      - "AWS_ACCESS_KEY_ID=IUbvAf6LS4zYsvZLaNLR"
      - "AWS_SECRET_ACCESS_KEY=quZScW8nZaATzVbwkKLk7DmlQvwqeHmHu3Qm5N3F"
```

You may add `S3_ENDPOINT` to something like `https://s3-us-west-2.amazonaws.com` or your custom S3 Endpoint like my docker compose above.

I'll update the README as soon as possible and please tell me what's work for you
